import torch
from PIL import Image
from transformers import (
    AutoProcessor,
    AutoModelForImageTextToText,
    BitsAndBytesConfig,
)

MODEL_ID = "google/medgemma-1.5-4b-it"

IMAGE_PATH = (
    r"results\rmscnn_xai\gradcam_results\colonca1208_gradcam.png"
)

print("=" * 60)
print("MedGemma 1.5 4B - Test")
print("=" * 60)

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    print(
        "GPU memory:",
        round(
            torch.cuda.get_device_properties(0).total_memory / 1024**3,
            2,
        ),
        "GB",
    )

# ---------------------------------------------------------
# 1. Load processor
# ---------------------------------------------------------

print("\nLoading processor...")

processor = AutoProcessor.from_pretrained(
    MODEL_ID,
    token=True,
)

print("Processor loaded.")

# ---------------------------------------------------------
# 2. 4-bit quantization configuration
# ---------------------------------------------------------

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# ---------------------------------------------------------
# 3. Load MedGemma
# ---------------------------------------------------------

print("\nLoading MedGemma in 4-bit mode...")
print("This may take several minutes on the first run.")

model = AutoModelForImageTextToText.from_pretrained(
    MODEL_ID,
    token=True,
    quantization_config=quantization_config,
    device_map="auto",
    torch_dtype=torch.float16,
)

print("\nModel loaded successfully.")

# ---------------------------------------------------------
# 4. Display device map
# ---------------------------------------------------------

print("\nDevice map:")
print(model.hf_device_map)

# ---------------------------------------------------------
# 5. Load RMSCNN Grad-CAM image
# ---------------------------------------------------------

print("\nLoading image:")

image = Image.open(IMAGE_PATH).convert("RGB")

print("Image:", IMAGE_PATH)
print("Image size:", image.size)

# ---------------------------------------------------------
# 6. VLM prompt
# ---------------------------------------------------------

prompt = """
You are assisting with a research project on colorectal cancer
histopathology image analysis.

The image contains a histopathology image with a Grad-CAM overlay
generated by an RMSCNN classification model.

Explain the following:

1. What visual regions appear to receive strong Grad-CAM activation?
2. What visible histopathological characteristics are present in
   those regions?
3. How might these characteristics relate to the model's prediction?
4. Clearly distinguish model attention from confirmed tumor
   segmentation.

Important requirements:

- Do not claim that a highlighted region is definitely cancer.
- Do not treat the Grad-CAM heatmap as a tumor segmentation mask.
- Do not provide a clinical diagnosis.
- Clearly state that Grad-CAM represents class-discriminative
  model attention.
- Give a concise, research-oriented explanation.
"""

# ---------------------------------------------------------
# 7. Prepare multimodal input
# ---------------------------------------------------------

print("\nPreparing multimodal input...")

messages = [
    {
        "role": "user",
        "content": [
            {
                "type": "image",
                "image": image,
            },
            {
                "type": "text",
                "text": prompt,
            },
        ],
    }
]

inputs = processor.apply_chat_template(
    messages,
    add_generation_prompt=True,
    tokenize=True,
    return_tensors="pt",
    return_dict=True,
)

# ---------------------------------------------------------
# 8. Move inputs to model device
# ---------------------------------------------------------

input_device = next(model.parameters()).device

inputs = {
    key: value.to(input_device)
    for key, value in inputs.items()
}

# ---------------------------------------------------------
# 9. Generate VLM response
# ---------------------------------------------------------

print("\nRunning MedGemma inference...")
print("Please wait...")

with torch.inference_mode():
    output = model.generate(
        **inputs,
        max_new_tokens=300,
        do_sample=False,
    )

# ---------------------------------------------------------
# 10. Decode response
# ---------------------------------------------------------

input_length = inputs["input_ids"].shape[-1]

generated_tokens = output[:, input_length:]

response = processor.batch_decode(
    generated_tokens,
    skip_special_tokens=True,
)[0]

# ---------------------------------------------------------
# 11. Display result
# ---------------------------------------------------------

print("\n" + "=" * 60)
print("MEDGEMMA RESPONSE")
print("=" * 60)

print(response)

print("\n" + "=" * 60)
print("TEST COMPLETED")
print("=" * 60)